version: "3.8"
services:
  redis:
    container_name: aviary-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/data/redis-data:/data
      - ./volumes/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes --requirepass "${REDIS_PASSWORD:-abcd1234}"

  postgres:
    container_name: aviary-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${PG_DATABASE:-qa_db}"
      POSTGRES_USER: "${PG_USER:-twave_01}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-twave_01password}"
      TZ: "Asia/Tokyo"
    volumes:
      - ./volumes/data/postgres-data:/var/lib/postgresql/data
